require("dotenv").config();
require("../db-conn");
const express = require("express");
const bodyParser = require("body-parser");

const app = express();
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
// gives server access to static files generated by running yarn build in client
app.use(express.static("./client/build/"));

// mount routes
app.use("/api/z3", require("./z3-route").router);
app.use("/api/global/", require("./global-route").router);
app.use("/api/device/", require("./device-route").router);
app.use("/api/deployment", require("./deployment-route").router);
app.use("/api/util", require("./util-route").router);
app.use("/api/template", require("./template-route").router);
app.use("/api/variant", require("./variant-route").router);
// the asterisk is very important!! as it allows client side routing
// with react-router or w/e client side routing package you use
app.get("/*", (req, res) => {
  console.log(__dirname);
  res.sendFile("index.html", { root: __dirname + "../../../client/build/" });
});

const port = process.env.PORT || 8001;
app.listen(port, () => console.log(`DivEnact running on port ${port}`));
